[default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
verbosity = 2
# Foundry is fast enough that we can ignore the cache for now
force = false
bytecode_hash = 'none'
solc_version = '0.8.13'
extra_output_files = ['abi']
